import { Link } from 'react-router';
import { Bed, Scissors, Camera, Utensils, HeartPulse, Sparkles, ArrowRight, CheckCircle, CalendarCheck, PhoneCall, PawPrint, Star } from 'lucide-react';

export default function Services() {
  const services = [
    { icon: Bed, name: '寵物住宿', description: '提供舒適安全的住宿環境，24小時專業照護', features: ['多種房型選擇', '24小時監控', '定期遛放', '即時回報'], bg: 'from-[#fdf6f0] to-[#f3e4d7]', iconBg: 'bg-[#6b3a2a]', accent: '#6b3a2a', link: '/rooms' },
    { icon: Scissors, name: '美容服務', description: '專業美容師團隊，提供全方位美容護理', features: ['洗澡護理', '造型設計', 'SPA護理', '專業剪毛'], bg: 'from-[#fff5f2] to-[#f6ddd5]', iconBg: 'bg-[#b87868]', accent: '#b87868', link: '/grooming' },
    { icon: Utensils, name: '餐食服務', description: '提供營養均衡的餐食，可客製化特殊需求', features: ['營養餐點', '特殊飲食', '定時餵食', '新鮮食材'], bg: 'from-[#f3f7f3] to-[#e0efe0]', iconBg: 'bg-[#5f8a5f]', accent: '#5f8a5f', link: '/booking' },
    { icon: HeartPulse, name: '健康照護', description: '定期健康檢查，確保毛孩身體狀況', features: ['健康檢查', '疫苗提醒', '用藥管理', '緊急處理'], bg: 'from-[#fff1ec] to-[#f4d6cc]', iconBg: 'bg-[#b85c38]', accent: '#b85c38', link: '/booking' },
    { icon: Camera, name: '即時回報', description: '透過照片與影片，隨時了解毛孩狀況', features: ['照片分享', '影片記錄', '每日報告', '即時通知'], bg: 'from-[#f4f3f7] to-[#e3e1ec]', iconBg: 'bg-[#6b6a8f]', accent: '#6b6a8f', link: '/booking' },
    { icon: Sparkles, name: '客製服務', description: '根據您的需求，提供專屬服務方案', features: ['個性化照護', '特殊需求', '長期方案', '專屬優惠'], bg: 'from-[#fff8f0] to-[#f2e6d8]', iconBg: 'bg-[#c8a15f]', accent: '#c8a15f', link: '/booking' },
  ];
  const steps = [
    { icon: CalendarCheck, title: '線上預約', description: '選擇服務項目、日期與毛孩資料' },
    { icon: PhoneCall, title: '確認預約', description: '專人與您確認服務細節與注意事項' },
    { icon: PawPrint, title: '享受服務', description: '由專業團隊進行住宿、美容或照護' },
    { icon: Star, title: '服務完成', description: '查看紀錄並分享您的服務評價' },
  ];

  return <div className="min-h-screen bg-[#fffefe]">
    <Hero />
    <section className="py-16 bg-white"><div className="max-w-7xl mx-auto px-4"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{services.map(service=>{const Icon=service.icon;return <div key={service.name} className="group rounded-3xl overflow-hidden bg-white shadow-md hover:shadow-2xl hover:-translate-y-2 transition-all duration-300 border border-[#f0e6df]"><div className={`relative p-8 bg-gradient-to-br ${service.bg}`}><div className="flex items-start justify-between gap-4 mb-6"><div className={`w-16 h-16 rounded-2xl flex items-center justify-center ${service.iconBg} group-hover:scale-110 transition-transform`}><Icon className="w-8 h-8 text-white" /></div><div className="text-xs px-3 py-1 rounded-full bg-white/80 shadow-sm" style={{ color: service.accent }}>專業服務</div></div><h3 className="text-2xl mb-2 text-[#3d1a0d]">{service.name}</h3><p className="text-sm leading-relaxed text-[#6b3a2a]">{service.description}</p></div><div className="p-6"><p className="text-sm text-gray-500 mb-3">服務內容</p><ul className="space-y-2 mb-6">{service.features.map(f=><li key={f} className="flex items-center gap-2 text-gray-700"><CheckCircle className="w-4 h-4 flex-shrink-0" style={{ color: service.accent }} /><span className="text-sm">{f}</span></li>)}</ul><Link to={service.link} className="inline-flex w-full items-center justify-center gap-2 py-3 rounded-full bg-[#6b3a2a] text-white hover:bg-[#8b5040] transition-all shadow-md hover:shadow-lg">了解更多 <ArrowRight className="w-4 h-4" /></Link></div></div>})}</div></div></section>
    <section className="py-16 bg-gradient-to-br from-[#fdf6f0] to-[#f5ede8]"><div className="max-w-7xl mx-auto px-4"><div className="text-center mb-12"><p className="text-sm mb-3 text-[#b87868]">PROCESS</p><h2 className="text-3xl text-[#3d1a0d]">服務流程</h2></div><div className="grid md:grid-cols-4 gap-6">{steps.map((step,index)=>{const Icon=step.icon;return <div key={step.title} className="relative bg-white rounded-3xl p-6 text-center shadow-md hover:shadow-xl transition-all border border-[#f0e6df]"><div className="absolute top-4 right-4 text-xs text-[#c8a97e]">0{index+1}</div><div className="w-16 h-16 bg-[#6b3a2a] text-white rounded-2xl flex items-center justify-center mx-auto mb-5"><Icon className="w-8 h-8" /></div><h3 className="text-lg mb-2 text-[#3d1a0d]">{step.title}</h3><p className="text-sm text-gray-600 leading-relaxed">{step.description}</p></div>})}</div></div></section>
    <section className="py-16 bg-white"><div className="max-w-5xl mx-auto px-4"><div className="relative overflow-hidden rounded-3xl p-12 text-center shadow-xl bg-gradient-to-br from-[#6b3a2a] to-[#8b5040] text-white"><div className="absolute left-8 top-8 text-7xl opacity-10">🐾</div><div className="absolute right-8 bottom-8 text-7xl opacity-10">🐕</div><h2 className="text-3xl mb-6 relative">準備好開始了嗎？</h2><p className="text-xl mb-10 leading-relaxed text-[#e8c9a0] relative">立即預約我們的服務，讓您的毛孩享受最安心的照護體驗。</p><Link to="/booking" className="relative inline-flex items-center gap-2 px-8 py-4 bg-white text-[#6b3a2a] rounded-full shadow-lg hover:shadow-xl hover:-translate-y-1 transition-all text-lg">立即預約 <ArrowRight className="w-5 h-5" /></Link></div></div></section>
  </div>;
}

function Hero() { return <section className="relative overflow-hidden py-20 bg-gradient-to-br from-[#fdf6f0] via-[#fff8f2] to-[#f5ede8]"><div className="absolute left-8 top-10 text-8xl opacity-10">🐾</div><div className="absolute right-10 bottom-8 text-8xl opacity-10">✨</div><div className="max-w-7xl mx-auto px-4 text-center relative"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/70 text-[#6b3a2a] text-sm shadow-sm mb-6"><Sparkles className="w-4 h-4" />全方位毛孩照護</div><h1 className="text-5xl mb-6 text-[#3d1a0d]">服務項目</h1><p className="text-xl text-[#6b3a2a] max-w-2xl mx-auto leading-relaxed">從住宿、美容、餐食到健康照護，提供毛孩完整又安心的服務體驗。</p></div></section>; }
